version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum ".circleci/config.yml" }}
      # install dependencies    
      - run:
          name: install dependencies
          command: npm install serverless
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum ".circleci/config.yml" }}
          paths: 
            - node_modules   
      - run:
          name: test
          command: npx sls --version

workflows:
  main:
    jobs:
      - build
